export const team: {
  name: string
  title: string
  image: string
  url: string
  department: string
}[] = [
  {
    name: 'Evan Ehlers',
    title: 'Executive Director, Founder',
    image: '/team/Evan.png',
    url: 'https://www.linkedin.com/in/evan-ehlers-9b4446a8/',
    department: 'leadership',
  },
  {
    name: 'Victoria Wilson',
    title: 'Director of Operations',
    image: '/team/Victoria.png',
    url: 'https://www.linkedin.com/in/wilsonvic/',
    department: 'leadership',
  },
  {
    name: 'Nourhan Ibrahim',
    title: 'Director of Development',
    image: '/team/Nourhan.png',
    url: 'https://www.linkedin.com/in/nourhan-s-ibrahim-61861a11b/',
    department: 'leadership',
  },
  {
    name: 'Alex Havertine',
    title: 'Director of Food Sourcing',
    image: '/team/Alex.png',
    url: 'https://www.linkedin.com/in/alexandra-havertine-ba5353123/',
    department: 'leadership',
  },
  {
    name: 'Sarah DiPasquale',
    title: 'Director of Food Distribution',
    image: '/team/Sarah.png',
    url: 'https://www.linkedin.com/in/sarah-dipasquale-350931129/',
    department: 'leadership',
  },
  {
    name: 'Ryan McHenry',
    title: 'Director of Technology',
    image: '/team/Ryan.png',
    url: 'https://www.linkedin.com/in/ryanmarshallmc/',
    department: 'leadership',
  },
  {
    name: 'Sonali Mehta',
    title: 'Director of Data Analytics',
    image: '/team/Sonali.png',
    url: 'https://www.linkedin.com/in/sonalimehta876/',
    department: 'leadership',
  },
  {
    name: 'Rachael Ihim',
    title: 'Marketing Coordinator',
    image: '/team/Rachael.png',
    url: 'https://www.linkedin.com/in/racheal-ihim-92467618a/',
    department: 'operations',
  },
  {
    name: 'Cara DePiano',
    title: 'Community Engagement Coordinator',
    image: '/team/Cara.png',
    url: 'https://www.linkedin.com/in/cara-d-476aa711a/',
    department: 'community engagement',
  },

  {
    name: 'Lucy Doren',
    title: 'Distribution Coordinator',
    image: '/team/Lucy.png',
    url: '',
    department: 'distribution',
  },
  {
    name: 'Amber Brouwer',
    title: 'Distribution Coordinator',
    image: '/team/Amber.png',
    url: 'https://www.linkedin.com/in/amber-brouwer/',
    department: 'distribution',
  },
  {
    name: 'Natalie Cleri',
    title: 'Distribution Coordinator',
    image: '/team/Natalie.png',
    url: 'https://www.linkedin.com/in/natalie-cleri-439155183/',
    department: 'distribution',
  },
  {
    name: 'Braden Walper',
    title: 'Food Sourcing Coordinator',
    image: '/team/Braden.png',
    url: 'https://www.linkedin.com/in/braden-walper-5b70b41a7/',
    department: 'distribution',
  },
  {
    name: 'Andre Powell',
    title: 'Food Sourcing Associate',
    image: '/team/Andre.png',
    url: 'https://www.linkedin.com/company/sharing-excess',
    department: 'distribution',
  },
  {
    name: 'Elle Palmer',
    title: 'Food Sourcing Associate',
    image: '/team/Elle.png',
    url: 'https://www.linkedin.com/company/sharing-excess/mycompany/',
    department: 'distribution',
  },
  {
    name: 'Matt Leger',
    title: 'Food Sourcing Associate',
    image: '/team/Matt.png',
    url: 'https://www.linkedin.com/in/matt-leger-116b51174/',
    department: 'distribution',
  },
  {
    name: 'Collin Young',
    title: 'Wholesale Rescue Coordinator',
    image: '/team/Collin.png',
    url: 'https://www.linkedin.com/in/collin-young-07aa041ab/',
    department: 'distribution',
  },
  {
    name: 'Harry Welsh',
    title: 'Warehouse Manager',
    image: '/team/Harry.png',
    url: 'https://www.linkedin.com/in/harry-welsh-0ba18a204/',
    department: 'operations',
  },
  {
    name: 'Atara Saunders',
    title: 'Fundraising Associate',
    image: '/team/Atara.png',
    url: 'https://www.linkedin.com/in/atara-saunders/',
    department: 'operations',
  },
  {
    name: 'Inara Pirani',
    title: 'Administrative Assistant',
    image: '/team/Inara.png',
    url: 'https://www.linkedin.com/in/inarapirani/',
    department: 'operations',
  },
  {
    name: 'Jaara Ndaw',
    title: 'Community Engagement Coordinator',
    image: '/team/Jaara.png',
    url: 'https://www.linkedin.com/in/jaara-ndaw-47322617b/',
    department: 'community engagement',
  },
  {
    name: 'Armando Parra',
    title: 'Software Engineer',
    image: '/team/Armando.png',
    url: 'https://www.linkedin.com/in/armando-parra-1bb2b2209/',
    department: 'technology',
  },
  {
    name: 'Oroghene Emudainohwo',
    title: 'Software Engineer',
    image: '/team/Roghe.png',
    url: 'https://www.linkedin.com/in/oroghene/',
    department: 'technology',
  },
  {
    name: 'Jill Tracy',
    title: 'UI/UX Designer',
    image: '/team/Jill.png',
    url: 'https://www.linkedin.com/in/jilliantracy/',
    department: 'technology',
  },
]
