export * from './Splash/Splash'
export * from './Problem/Problem'
export * from './Solution/Solution'
export * from './Impact/Impact'
export * from './News/News'
export * from './Volunteer/Volunteer'
export * from './Donate/Donate'
